spring:
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
  profiles:
    active: dev